spring.application.name=login-auth-api

# TiDB Cloud Database
spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/login_auth_db?sslMode=VERIFY_IDENTITY&enabledTLSProtocols=TLSv1.2
spring.datasource.username=2tB52fqXCx54AyK.root
spring.datasource.password=VunhHSy2dwgHzT7S

# MySQL Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=MaheshLoginAuthApiSecretKey12345678901234567890
jwt.expiration=3600000