spring.application.name=login-auth-api

spring.datasource.url=jdbc:mysql://localhost:3306/login_auth_db
spring.datasource.username=root
spring.datasource.password=Mahesh@748

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=MaheshLoginAuthApiSecretKey12345678901234567890
jwt.expiration=3600000